apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: healthz
  labels:
    app: healthz
  namespace: ns-xyz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthz
  template:
    metadata:
      labels:
        app: healthz
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: healthz
        # Any image is permissible as long as:
        # 1. It serves a 404 page at /
        # 2. It serves 200 on a /healthz endpoint
        image: chimpwizard/healthz
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8080
        #     scheme: HTTP
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 5
        ports:
        - name: http
          containerPort: 8080
        resources:
          # limits:
          #   cpu: 10m
          #   memory: 20Mi
          # requests:
          #   cpu: 10m
          #   memory: 20Mi